### ISSUE TITLE
Discriminator output lopsided

### ISSUE THREAD

**Issue by jerrywyn** [ggsDing/ASLNet#5]
Is it normal that when I use the discriminator to learn the prediction results and the label, I find that the output and the loss are very unbalanced, i.e. the discriminator output tends to output 0. Is this normal? I feel that the discriminator has not been trained.
![90CFFABE029B69CA9A48EE07EF5AB086](https://user-images.githubusercontent.com/48412363/197389581-c0ab3f15-19d7-4096-8932-455877215c19.png)

**Comment by DingLei14** [comment]
Hi. Of course, this means failure of the training. I do not know what's the cause though. Are you doing building extraction or other task?

**Comment by epoch8260** [comment]
> 

you are not alone. This article may be 造假的

**Comment by ggsDing** [comment]
> > 
> 
> you are not alone. This article may be 造假的

Hi. It's very impolite to comment like that. GANs are known for unstable during training. In the other issue I already provided you the checkpoint as you asked. Do you really think I faked all the visualization results?
